name: festiva
description: "A new Flutter project."
publish_to: "none"

version: 1.0.10+14

environment:
  sdk: ^3.6.1

dependencies:
  cached_network_image: ^3.4.1
  change_app_package_name: ^1.5.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.8.0+1
  firebase_auth: ^5.5.4
  firebase_core: ^3.10.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.4
  fluttertoast: ^8.2.10
  geolocator: ^13.0.2
  get_it: ^8.0.3
  go_router: ^16.0.0
  google_sign_in: ^6.3.0
  http: ^1.3.0
  image: ^4.5.3
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.6.0
  mapbox_maps_flutter: ^2.9.0
  path_provider: ^2.1.5
  pretty_dio_logger: ^1.4.0
  provider: ^6.1.2
  shared_preferences: ^2.5.1
  shimmer: ^3.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.3

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
